#### Perceptron Model

##### Installing Tensorflow
- pip install tensorflow

tensorflow is a powerful open-source library for machine learning and deep learning. It provides a flexible ecosystem of tools, libraries, and community resources that lets researchers and developers build and deploy machine learning models easily. With TensorFlow, you can create complex neural networks, perform data manipulation, and run computations efficiently on various hardware platforms, including CPUs, GPUs, and TPUs. Whether you're working on image recognition, natural language processing, or any other machine learning task, TensorFlow offers the capabilities to help you achieve your goals.

##### Installing Keras
- pip install keras

keras is a high-level neural networks API, written in Python and capable of running on top of TensorFlow.

##### Step-1 Business Problem Understanding
Predict/estimate the wind energy based on atmospheric conditions

##### Step-2 
- Load the data 
- data understanding
- data exploration

In [33]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_excel("energy.xlsx")
df

,AT,V,AP,RH,PE
0,14.96,41.76,1024.07,73.17,463.26
1,25.18,62.96,1020.04,59.08,444.37
2,5.11,39.40,1012.16,92.14,488.56
3,20.86,57.32,1010.24,76.64,446.48
4,10.82,37.50,1009.23,96.62,473.90
...,...,...,...,...,...
9563,16.65,49.69,1014.01,91.00,460.03
9564,13.19,39.18,1023.67,66.78,469.62
9565,31.32,74.33,1012.92,36.48,429.57
9566,24.48,69.45,1013.86,62.39,435.74


In [35]:
df.shape

(9568, 5)

**Data Understanding**

In [36]:
df.columns.tolist()

['AT', 'V', 'AP', 'RH', 'PE']

**Data Exploration**

In [37]:
df["AT"].unique()

array([14.96, 25.18,  5.11, ..., 30.  ,  5.01,  9.71], shape=(2773,))

In [38]:
df["AP"].unique()

array([1024.07, 1020.04, 1012.16, ..., 1027.12, 1024.16, 1023.67],
      shape=(2517,))

**Data Cleaning**

In [39]:
l = []
for i in df["AP"] : 
    if type(i) not in [int, float] : 
        l.append(i)
print(l)

[]


In [40]:
## if wrong data is there then we can drop that row or we can fill that row with mean or median value of that column.
df[df["AP"] == "no data"].index.tolist()
df.loc[258, "AP"] = df["AP"].mean() # or replace with orginal data if you have that data

**Input and Ouput Variables**

In [41]:
x = df.drop("PE", axis=1)
y = df["PE"]

**Splitting the data into training and testing data**

In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# above code will split the data into 80% training data and 20% testing data. random_state is used to get the same split every time we run the code.
# random_state is used to get the same split every time we run the code. if we do not set random_state then we will get different split every time we run the code.
# we can set any number for random_state. 

In [43]:
x_train

,AT,V,AP,RH
5487,21.92,49.02,1009.29,88.56
3522,11.09,40.43,1025.47,74.97
6916,8.49,39.61,1021.05,87.74
7544,11.43,44.78,1013.43,82.45
7600,17.28,39.99,1007.09,74.25
...,...,...,...,...
5734,23.39,61.87,1010.35,48.91
5191,11.63,40.55,1022.89,87.12
5390,27.79,69.23,1012.86,45.71
860,12.26,41.50,1014.87,89.41


In [44]:
y_train

5487    443.31
3522    490.96
6916    483.94
7544    471.09
7600    463.28
         ...  
5734    444.03
5191    474.67
5390    435.06
860     471.13
7270    472.43
Name: PE, Length: 7654, dtype: float64

##### Perceptron

In [45]:
import tensorflow as tf
import keras

In [46]:
from keras.models import Sequential
from keras.layers import Dense

**Design the perceptron model**

In [47]:
## initialize of neural network
model = Sequential()

## add input layer and first hidden layer
model.add(Dense(input_dim=4, units=1, activation="relu", kernel_initializer="uniform")) 
# input_dim is number of features in the data. units is number of neurons in the hidden layer. activation is activation function used in the hidden layer.
# kernel_initializer is used to initialize the weights of the neurons. we can use uniform or normal distribution to initialize the weights.
# dense connects all the neurons in the previous layer to all the neurons in the next layer.

# compile - calculate the loss and optimizer
model.compile(loss="mean_squared_error", optimizer="adam")

c:\Users\nirmi\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [48]:
# fit the train data to the model for calculating the weights and bias of the neurons.
model.fit(x_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 847us/step - loss: 206799.0312
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - loss: 206799.1562
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 206799.1250
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 206799.1406
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 206799.0938
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - loss: 206799.0625
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 206799.0781
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - loss: 206799.0312
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - loss: 206799.0469
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - loss: 206799.1562
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 206799.0312
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - loss: 206799.0625
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 206799.2031
Epoch 14/100
240/240 

In [49]:
### Prediction on train data
y_train_pred = model.predict(x_train)
y_train_pred

## evaluate the train data
from sklearn.metrics import mean_squared_error
mse_train = mean_squared_error(y_train, y_train_pred)
print("Mean Squared Error on Train Data: ", mse_train)
print("Train RMSE: ", np.sqrt(mse_train))

240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 605us/step
Mean Squared Error on Train Data:  206799.09872754116
Train RMSE:  454.7516890870678


#### ANN Model
- design
- fit
- predict
- evaluation (RMSE)

In [50]:
# initoalization of neural network
nn1 = Sequential()

# add input layer and hidden layer
nn1.add(Dense(input_dim=4, units=8, activation="relu", kernel_initializer="uniform"))
nn1.add(Dense(units=1, activation="relu", kernel_initializer="uniform"))

# compile the model
nn1.compile(loss="mean_squared_error", optimizer="adam")

c:\Users\nirmi\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [51]:
nn1.fit(x_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 834us/step - loss: 105028.7734
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - loss: 631.6174 
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - loss: 410.9936
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - loss: 393.7881
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 374.0228
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - loss: 351.5226
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - loss: 327.5745
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - loss: 302.1023
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 275.6603
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - loss: 249.0524
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - loss: 222.5508
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 197.2623
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - loss: 173.4088
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step 

In [52]:
## Prediction on train data
y_train_pred = nn1.predict(x_train)

240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step


In [53]:
## evaluate the train data
from sklearn.metrics import mean_squared_error
mse_train = mean_squared_error(y_train, y_train_pred)
print("Mean Squared Error on Train Data: ", mse_train)
print("Train RMSE: ", np.sqrt(mse_train))

Mean Squared Error on Train Data:  26.773773656191093
Train RMSE:  5.174337992071169


**With 2 hidden layer**

In [54]:
nn2 = Sequential()
nn2.add(Dense(input_dim=4, units=8, activation="relu", kernel_initializer="uniform"))
nn2.add(Dense(units=8, activation="relu", kernel_initializer="uniform"))
nn2.add(Dense(units=1, activation="relu", kernel_initializer="uniform"))
nn2.compile(loss="mean_squared_error", optimizer="adam")
nn2.fit(x_train, y_train, epochs=100, batch_size=32)
y_train_pred = nn2.predict(x_train)
mse_train = mean_squared_error(y_train, y_train_pred)
print("Mean Squared Error on Train Data: ", mse_train)
print("Train RMSE: ", np.sqrt(mse_train))

Epoch 1/100


c:\Users\nirmi\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 100506.8906  
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - loss: 414.6653
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - loss: 390.7022
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - loss: 362.0414
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - loss: 328.9714
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - loss: 295.1939
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - loss: 260.5521
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - loss: 226.6047
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - loss: 194.4459
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - loss: 165.1787
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - loss: 138.4050
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - loss: 115.9592
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - loss: 97.7079 
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - loss: 82.02

Once all epochs are completed , after last epoch : weights will be stored and used for future prediction.

Train RMSE == Train RMSE (good model) +-5% : Here we can say that our model is good because train RMSE and test RMSE are almost same.

Train RMSE > Test RMSE (underfitting problem) : Here we can say that our model is underfitting because train RMSE is greater than test RMSE. it means that our model is not able to capture the underlying pattern of the data.
- Model not performed well on trained data
- Model performed well on tested data
- Solution : Add more amount of data (add more records)

Train RMSE < Test RMSE (overfitting problem) : Here we can say that our model is overfitting because train RMSE is less than test RMSE. it means that our model is too complex and is memorizing the training data instead of learning the underlying pattern.
- Model performed well on trained data
- Model not performed well on tested data
- Solution : depends on algorithm

**Improve the accuracy in ANN**
1. Valid data cleaning
2. increase epochs
3. increase hidden layers
4. increase batch_size


**Model Selection**
: Within multiple good models, the model which gives least error is the best model

**Prediction on the future data**

In [57]:
import pandas as pd
## Future Prediction to predict the future value of PE for given values of AT, V, AP and RH
fut = pd.DataFrame({"AT" : [20] , "V" : [60] , "AP" : [1050] , "RH" : [70]})
fut

,AT,V,AP,RH
0,20,60,1050,70


In [58]:
nn2.predict(fut)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[468.72833]], dtype=float32)