**OpenCV installation can be done in 2 ways**
- conda install -c conda-froge opencv
- pip install opencv-python

In [2]:
import cv2
import numpy as np

#### Load / Read Image

In [3]:
# Load an image using imread function
img = cv2.imread('D:\\AI-Workspace\\5.Deep-Learning\\Narendra-Modi.jpeg' , 1) # 1 for color image, 0 for grayscale, -1 for unchanged

In [4]:
print(img) # It will print the pixel values of the image in the form of a numpy array.
# Img is a 3D numpy array of shape (height, width, channels) where channels are in BGR format.
# It is stored in the form of a numpy array. Each pixel value is represented as a list of 
# three values corresponding to the Blue, Green, and Red channels respectively. 
# The pixel values range from 0 to 255, where 0 represents no intensity and 255 represents full intensity for that channel.

[[[121 121 121]
  [120 120 120]
  [119 119 119]
  ...
  [144 144 144]
  [145 145 145]
  [145 145 145]]

 [[120 120 120]
  [119 119 119]
  [120 120 120]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 [[119 119 119]
  [119 119 119]
  [119 119 119]
  ...
  [145 145 145]
  [145 145 145]
  [145 145 145]]

 ...

 [[175 175 175]
  [175 175 175]
  [174 174 174]
  ...
  [233 233 233]
  [233 233 233]
  [233 233 233]]

 [[174 174 174]
  [175 175 175]
  [175 175 175]
  ...
  [233 233 233]
  [233 233 233]
  [233 233 233]]

 [[175 175 175]
  [175 175 175]
  [175 175 175]
  ...
  [233 233 233]
  [233 233 233]
  [233 233 233]]]


In [5]:
img.shape # It will print the shape of the image in the form of a tuple (height, width, channels).
# channels is 3 for color images (BGR) and 1 for grayscale images. 
# The shape of the image is represented as a tuple (height, width, channels)
#  where height is the number of rows, width is the number of columns, 
# and channels represent the number of color channels in the image.

(1202, 1431, 3)

#### Display the image

In [6]:
# To display our image variable, we use 'imshow'
# The first parameter will be title shown on image window
# The second parameter is the image varialbe
cv2.imshow('PM', img)

# 'waitkey' allows us to input information when a image window is open
# By Leaving it blank it just waits for anykey to be pressed before continuing.
# By placing numbers (except 0), we can specify a delay for
# how Long you keep the window open (time is in milliseconds here)
cv2.waitKey()

# This closes all open windows
# Failure to place this will cause your program to hang
cv2.destroyAllWindows()

#### Save the image

In [7]:
# Simply use 'imwrite' specificing the file name and the image to be saved
cv2.imwrite("pm_b_w.jpg", img)

True

#### Resize the image

In [8]:
resized_image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

cv2.imshow('Modi Image', gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
print(img.shape) # It will print the shape of the image in the form of a tuple (height, width, channels).

(1202, 1431, 3)


#### Face Detction using Haar Cascades
- Haar Cascade is a machine learning based approach where a cascade function is trained from a lot of positive and negative images. It is then used to detect objects in other images.
- OpenCV provides pre-trained Haar Cascade models for various objects, including faces.

In [10]:
# Load the image
image = cv2.imread('D:\\AI-Workspace\\5.Deep-Learning\\Narendra-Modi.jpeg')

# resize the image to a specific size (e.g., 300x300)
resized_image = cv2.resize(image, (700, 700))

# convert the image to grayscale bcz many computer vision algorithms 
# work better on single channel images
gray_image = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

In [11]:
# Load the features of the object to be detected
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
# Here we are using the Haar Cascade Classifier for frontal face detection, 
# which is a pre-trained model provided by OpenCV. The 'haarcascade_frontalface_default.xml'
# file contains the features and patterns that the classifier uses to identify faces in an image.

faces = face_cascade.detectMultiScale(gray_image, scaleFactor=1.1, minNeighbors=5)
# The 'detectMultiScale' method detects objects (in this case, faces) in the input image.
# The 'scaleFactor' parameter specifies how much the image size is reduced at each image scale
# (e.g., 1.1 means the image is reduced by 10% at each scale). 
# The 'minNeighbors' parameter specifies how many neighbors each candidate rectangle should have to retain it (e.g., 5 means
# that a rectangle should have at least 5 neighbors to be considered a valid detection).

In [12]:
print(faces) # It will print the coordinates of the detected faces in the form of a list of rectangles.
# Each rectangle is represented as a list of four values [x, y, w, h], 
# where (x, y) is the top-left corner of the rectangle,
#  and (w, h) are the width and height of the rectangle respectively.

[[263 101 178 178]]


In [ ]:
### Tuning Cascade Classifiers - detectMultiScale(input image, ** Scale Factor **, ** Min Neighbors ** )
face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Load our image then convert it to grayscale
img = cv2.resize(image,(500,500))
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

### Tuning Cascade Classifiers - detectMultiScale(input image, ** Scale Factor **, ** Min Neighbors ** )
faces = face_classifier.detectMultiScale(gray, scaleFactor=1.05, minNeighbors=5)

# Scale Factor
# E.g. in face detection we typically use 1.3. This means we reduce the image by 30% each time it's scaled.
# Smaller values, like 1.05 will take Longer to compute, but will increase the rate of detection.

## Min Neighbors **
# Specifies the number of neighbors each potential window should have in order to consider it a positive detection.
# Typically set between 3-6.
# It acts as sensitivity setting, low values will sometimes detect multiples faces over a single face.
# High values will ensure Less false positives, but you may miss some faces.

# When no faces detected, face_classifier returns and empty tuple
if faces is ():
    print("No faces found")

# We iterate through our faces array and draw a rectangle
# over each face in faces
for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y),(x+w,y+h), (0,255,100), 1) # The 'rectangle' function draws a rectangle on the image.
    # The first parameter is the image on which to draw the rectangle.
    # The second parameter is the top-left corner of the rectangle (x, y).
    # The third parameter is the bottom-right corner of the rectangle (x + w, y + h).
    # The fourth parameter is the color of the rectangle in BGR format (0, 255, 100) which is a shade of green.
    # The fifth parameter is the thickness of the rectangle border (1 in this case).

cv2.imshow('Face Detection', img)
cv2.waitKey()
cv2.destroyAllWindows()

#### Face & Eye Detection using HAAR Cascade Classifier in Image

In [17]:
face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

faces = face_classifier.detectMultiScale(gray, scaleFactor=1.05, minNeighbors=5)

if faces is ():
    print("No faces found")

for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y),(x+w,y+h), (0,255,100), 1)
    roi_gray = gray[y:y+h, x:x+w] # Region of Interest in grayscale
    roi_color = img[y:y+h, x:x+w] # Region of Interest in color
    eyes = eye_classifier.detectMultiScale(roi_gray) # Detect eyes within the face region
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color, (ex,ey),(ex+ew,ey+eh), (255,0,0), 1) # Draw rectangle around detected eyes

## Above code detects faces and then within each detected face, it detects eyes.
# The rectangles for faces are drawn in green, while the rectangles for eyes are drawn in blue. 
# The 'roi_gray' and 'roi_color' variables represent the region of interest for the detected face,
# which is used to detect eyes within that specific area of the image.
# This approach helps to improve the accuracy of eye detection by focusing on 
# the area where eyes are likely to be located (within the detected face region).

cv2.imshow('Face and Eye Detection', img)
cv2.waitKey()
cv2.destroyAllWindows()

#### Capture a video

In [1]:
# Doing some Face Recognition with the web came

import cv2

video = cv2.VideoCapture(0) # 0 for default webcam, you can specify other numbers for different cameras

while True:
    check, frame = video.read() # Read a frame from the webcam
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # Convert the frame to grayscale
    cv2.imshow('Webcam', gray) # Display the grayscale frame in a window titled 'Webcam'

    if cv2.waitKey(1) == ord('q'): # Wait for the 'q' key to be pressed to exit the loop
        break

## we are feeling as video but it is actually a series of images (frames) being captured 
# and displayed in quick succession, creating the illusion of motion.
video.release() # Release the webcam resource
cv2.destroyAllWindows() # Close all OpenCV windows

#### Face & Eye Detection using HAAR Cascade Classifier

In [2]:
# Defining a function that will do the detection
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

def detect(gray, frame):
    faces = face_cascade.detectMultiScale(gray, 1.3, 5) # Detect faces in the grayscale frame
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (0,255,100), 1) # Draw rectangle around detected face
        roi_gray = gray[y:y+h, x:x+w] # Region of Interest in grayscale
        roi_color = frame[y:y+h, x:x+w] # Region of Interest in color
        eyes = eye_cascade.detectMultiScale(roi_gray) # Detect eyes within the face region
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color, (ex,ey),(ex+ew,ey+eh), (255,0,0), 1) # Draw rectangle around detected eyes
    return frame

# Now we will use this function in our video loop
video = cv2.VideoCapture(0)
while True:
    check, frame = video.read() # Read a frame from the webcam
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # Convert the frame to grayscale
    canvas = detect(gray, frame) # Call the detect function to perform face and eye detection
    cv2.imshow('Face and Eye Detection', canvas) # Display the processed frame in a window titled 'Face and Eye Detection'

    if cv2.waitKey(1) == ord('q'): # Wait for the 'q' key to be pressed to exit the loop
        break
video.release() # Release the webcam resource
cv2.destroyAllWindows() # Close all OpenCV windows

#### Pedistrian Detection

In [6]:
import cv2 

# Create our body classifier
body_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_fullbody.xml')

# Initiate video capture for video file
cap = cv2.VideoCapture('D:\\AI-Workspace\\5.Deep-Learning\\people-walking.mp4')


while cap.isOpened():
    check, frame = cap.read() # Read a frame from the video
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # Convert the frame to grayscale
    bodies = body_classifier.detectMultiScale(gray, 1.2, 3) # Detect bodies in the grayscale frame
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (0,255,255), 1) # Draw rectangle around detected body
    cv2.imshow('Body Detection', frame) # Display the processed frame in a window titled
    if cv2.waitKey(1) == ord('q'): # Wait for the 'q' key to be pressed to exit the loop
        break

cap.release() # Release the video resource
cv2.destroyAllWindows() # Close all OpenCV windows