### NumPy
**(Numerical Python)**

- Used for working with arrays.
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy is incredible library to perform mathematical and statistical operations due to it's fast and memory efficient as it is optimized to work with latest CPU architectures.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. So processes can access and manipulate them very efficiently.

In [4]:
import numpy as np

#### NumPy Arrays
> List - No for loop is added  
> Array - Default for loop is added
#### 0-D

In [3]:
a = 45
print(a)
print(type(a))

45
<class 'int'>


In [4]:
a = 45
arr_0 = np.array(a)
print(arr_0)
print(type(arr_0))

45
<class 'numpy.ndarray'>


In [5]:
arr_0.ndim

0

In [6]:
arr_0.shape

()

#### 1-D

In [7]:
a = [1, 2, 3]
arr_1 = np.array(a)
print(arr_1)

[1 2 3]


In [8]:
arr_1.ndim

1

In [9]:
arr_1.shape

(3,)

##### Functions for creating 1D array

arange
- arange is an array-valued version of the built-in Python range function
- **Syntax:** `np.arange(start, end, step)`

In [13]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


linspace
- Return evenly spaced numbers over a specified interval.
- **Syntax:** `np.linspace(start, end, num_of_samples)`

In [14]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

zeros
- Generate arrays of zeros
- **Syntax:** `np.zeros(shape)`

In [15]:
np.zeros((2,))

array([0., 0.])

ones
- Generate arrays of ones
- **Syntax:** `np.ones(shape)`

In [16]:
np.ones((2,))

array([1., 1.])

random.randint
- Return random integers from start (inclusive) to end (exclusive)
- **Syntax:** `np.random.randint(start, end, num_of_samples)`

In [17]:
np.random.randint(1, 1000, 5)

array([783, 738, 715, 135, 487], dtype=int32)

##### Accessing elements / Extracting the values
1. Accessing a single value through Indexing
2. Accessing multiple values based on slicing
3. Accessing multiple values based on indexing
4. Accessing multiple values based on condition

In [18]:
a = np.arange(10, 51, 10)
print(a)

[10 20 30 40 50]


1. Accessing a single value through Indexing

In [19]:
# positive indexing
a[1]

np.int64(20)

In [20]:
# negative indexing
a[-1]

np.int64(50)

2. Accessing multiple values based on slicing

In [21]:
a[1:5:2]

array([20, 40])

In [22]:
a[-1:-4:-1]

array([50, 40, 30])

3. Accessing multiple values based on indexing

Syntax: `array[list of index numbers]`

In [23]:
a[[0, 3, 2, 4]]

array([10, 40, 30, 50])

4. Accessing multiple values based on condition (Mask Indexing or Fancy Indexing)

Syntax: `array[condition]`

-- first, it will check the condition; the item which satisfies the condition (means which item gives True for the condition), that item will be selected

In [24]:
a = np.array([45, 46, 47])
a[a % 2 == 0]

array([46])

##### Modify the values in Numpy

Add a single value in an array
Syntax: `np.append(array, value)`

In [25]:
a = np.array([45, 46, 47])
a1 = np.append(a, 110)
print(a1)

[ 45  46  47 110]


Add multiple values in an array

In [26]:
a = np.array([45, 46, 47])
a2 = np.append(a, [140, 120, 130])
print(a2)

[ 45  46  47 140 120 130]


Replacing a single value in a 1D array

In [27]:
a[0] = 150
print(a)

[150  46  47]


Replacing multiple values with a single value in an array

In [28]:
a[[1, 2]] = 15
a

array([150,  15,  15])

Replacing multiple values with multiple values in an array

In [29]:
a[[1, 2]] = [460, 14]
a

array([150, 460,  14])

Delete a single value in an array
Syntax: `np.delete(array, indexnumber)`

In [30]:
a3 = np.delete(a, 1)
print(a3)

[150  14]


Delete multiple values in an array
Syntax: `np.delete(array, [multiple index numbers])`

In [31]:
a4 = np.delete(a, [1, 2])  # deleting multiple values
print(a4)

[150]


##### Copy array

In [32]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


##### Sorting an Array

In [33]:
a = np.array([4, 6, 8, 2, 1])
b = np.sort(a)
print(b)

[1 2 4 6 8]


#### Operations

##### Arithmetic Operations

In [34]:
a = np.array([1, 2, 3, 4])

In [35]:
b = a + 1
print(b)

[2 3 4 5]


In [36]:
c = a + 0
print(c)

[1 2 3 4]


In [37]:
d = a ** 2
print(d)

[ 1  4  9 16]


In [38]:
print(a + b)

[3 5 7 9]


In [39]:
print(a - b)

[-1 -1 -1 -1]


In [40]:
print(a * b)

[ 2  6 12 20]


##### Comparison Operations

In [41]:
a == c

array([ True,  True,  True,  True])

In [42]:
c >= a

array([ True,  True,  True,  True])

In [43]:
np.array_equal(a, b)

False

In [44]:
np.array_equal(a, c)

True

##### Mathematical Operations

In [45]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [46]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [47]:
import warnings
warnings.simplefilter("ignore")

#### 2D Numpy Array

In [48]:
b = np.array([[0, 1, 2, 5], [2, 3, 4, 8]])
print(b)

[[0 1 2 5]
 [2 3 4 8]]


In [49]:
b.ndim

2

In [50]:
b.shape

(2, 4)

Combining 1D --> 2D ,
Combining 2D --> 3D

In [ ]:
a = [[1, 2, 3]]
arr_2 = np.array(a)
print(arr_2)

[[1 2 3]]


In [ ]:
arr_2.ndim

2

In [ ]:
arr_2.shape

(1, 3)

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
# Every 1D should have same shape
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [10]:
# 3D array
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a)
print(a.ndim)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [51]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros((3, 3), dtype=int) + 5


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [53]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
# identity matrix
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye(4, 3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [55]:
# diagonal matrix
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [56]:
# diagonal matrix
a = np.array([[1, 2, 3], [3, 4, 5]])
np.diag(a)

array([1, 4])

In [57]:
a = np.array([[10, 20, 50], [30, 40, 60], [20, 80, 90]])
print(a)

[[10 20 50]
 [30 40 60]
 [20 80 90]]


##### Indexing of 2D array

Extract the single row

In [58]:
a[0]  # all columns by default

array([10, 20, 50])

In [59]:
a[2, 2]

np.int64(90)

In [60]:
a[1:3]

array([[30, 40, 60],
       [20, 80, 90]])

In [61]:
# assigning value in 2d array
a[1] = [25, 30, 60]
a

array([[10, 20, 50],
       [25, 30, 60],
       [20, 80, 90]])

In [62]:
a[0, 2] = 500
a

array([[ 10,  20, 500],
       [ 25,  30,  60],
       [ 20,  80,  90]])

Extract the multiple rows

In [13]:
a = np.array([[11,20,45],[15,24,50], [19,32,51], [40,36,42], [50,90,96]])
print(a)

[[11 20 45]
 [15 24 50]
 [19 32 51]
 [40 36 42]
 [50 90 96]]


In [14]:
a[0:3 , :]

array([[11, 20, 45],
       [15, 24, 50],
       [19, 32, 51]])

In [15]:
a[[1,2,4] , :]

array([[15, 24, 50],
       [19, 32, 51],
       [50, 90, 96]])

In [16]:
a[[1,2,0,4] , :]

array([[15, 24, 50],
       [19, 32, 51],
       [11, 20, 45],
       [50, 90, 96]])

In [17]:
a[0:5:2 , :]

array([[11, 20, 45],
       [19, 32, 51],
       [50, 90, 96]])

Extract column

In [19]:
a[:,1]

array([20, 24, 32, 36, 90])

In [20]:
a[: , [1,2]]

array([[20, 45],
       [24, 50],
       [32, 51],
       [36, 42],
       [90, 96]])

##### Manipulation
Replace

In [22]:
a[1 , :] = [100, 200, 300]
print(a)

[[ 11  20  45]
 [100 200 300]
 [ 19  32  51]
 [ 40  36  42]
 [ 50  90  96]]


In [24]:
a[[0,2] , :] = 20
print(a)
a[[0,2] , :] = [40, 50, 60] , [100, 200, 300]
print(a)

[[ 20  20  20]
 [100 200 300]
 [ 20  20  20]
 [ 40  36  42]
 [ 50  90  96]]
[[ 40  50  60]
 [100 200 300]
 [100 200 300]
 [ 40  36  42]
 [ 50  90  96]]


delete

In [28]:
a5 = np.array([[11,20,45],[15,24,50], [19,32,51], [40,36,42], [50,90,96]])
print(a5)

[[11 20 45]
 [15 24 50]
 [19 32 51]
 [40 36 42]
 [50 90 96]]


In [29]:
# delete a single row
a5 = np.delete(a5, 1, axis=0)
print(a5)

[[11 20 45]
 [19 32 51]
 [40 36 42]
 [50 90 96]]


In [30]:
# delete multiple rows
a5 = np.delete(a5, [1, 2], axis=0)
print(a5)

[[11 20 45]
 [50 90 96]]


In [31]:
a5 = np.array([[11,20,45],[15,24,50], [19,32,51], [40,36,42], [50,90,96]])
print(a5)

[[11 20 45]
 [15 24 50]
 [19 32 51]
 [40 36 42]
 [50 90 96]]


In [32]:
# delete single column
a5 = np.delete(a5, 1, axis=1)
print(a5)

[[11 45]
 [15 50]
 [19 51]
 [40 42]
 [50 96]]


#### Flattening: Converting nd array to 1D array

In [ ]:
# Converting 2D array to 1D array
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a)

b = a.ravel()
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


#### Reshape array

In [64]:
arr = np.arange(6)
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
(6,)


In [ ]:
# Converting 1D array to 2D array
a1 = arr.reshape(2, 3)
print(a1)

[[0 1 2]
 [3 4 5]]


In [66]:
a = np.array([[0, 1, 5], [10, 50, 8]])
print(a)
print(a.shape)

[[ 0  1  5]
 [10 50  8]]
(2, 3)


In [67]:
print(a.reshape(3, 2))

[[ 0  1]
 [ 5 10]
 [50  8]]


In [68]:
c = a.T
print(c)

[[ 0 10]
 [ 1 50]
 [ 5  8]]


##### Sort
Sorting along an axis: `axis=1` --> row and `axis=0` --> column

In [34]:
# Column-wise sorting
a = np.array([[5, 4, 6], [2, 8, 2], [8, 9, 20]])
b = np.sort(a, axis=0)
b

array([[ 2,  4,  2],
       [ 5,  8,  6],
       [ 8,  9, 20]])

In [35]:
# Row-wise sorting
b = np.sort(a, axis=1)
b

array([[ 4,  5,  6],
       [ 2,  2,  8],
       [ 8,  9, 20]])

In [70]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[40, 4], [14, 24], [34, 44]])

# adding a and b
print(a + b)

[[41  6]
 [17 28]
 [39 50]]


In [71]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# dot product (multiply a and b - elementwise multiplication)
print(a * b)

[[ 5 12]
 [21 32]]


In [6]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a==3)
print(a==b)

[[False False]
 [ True False]]
[[False False]
 [False False]]


In [72]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# matrix multiplication
np.matmul(a, b)

array([[19, 22],
       [43, 50]])

In [ ]:
## Combinning arrays
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [74]:
# vertical stack (equal to np.concatenate((a,b), axis=0))
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [77]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [76]:
# horizontal stack (equal to np.concatenate((a,b), axis=1))
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])